		dc.b 0, $16
		dc.b btnR, $31
		dc.b btnR+btnC, $E
		dc.b btnR, 3
		dc.b 0, $20
		dc.b btnR, $17
		dc.b 0, $1F
		dc.b btnR, $12
		dc.b 0, $13
		dc.b btnR, $55
		dc.b btnR+btnC, 4
		dc.b btnC, 3
		dc.b 0, $16
		dc.b btnR, $30
		dc.b btnR+btnC, 0
		dc.b btnC, $A
		dc.b 0, $1A
		dc.b btnL, $11
		dc.b btnL+btnC, $10
		dc.b btnL+btnUp+btnC, 0
		dc.b btnL+btnUp, $11
		dc.b btnL, 7
		dc.b 0, $C
		dc.b btnR, $1B
		dc.b 0, $11
		dc.b btnR, 8
		dc.b btnR+btnC, $13
		dc.b btnR, 0
		dc.b 0, $11
		dc.b btnL, 4
		dc.b 0, $C
		dc.b btnR, $7C
		dc.b btnR+btnC, $F
		dc.b 0, $35
		dc.b btnL, $D
		dc.b btnL+btnC, $A
		dc.b btnL, 1
		dc.b 0, $E
		dc.b btnR, $8D
		dc.b 0, $1C
		dc.b btnL, $17
		dc.b 0, 3
		dc.b btnL, 5
		dc.b 0, 6
		dc.b btnR, $2A
		dc.b 0, $2E
		dc.b btnR, 7
		dc.b 0, $10
		dc.b btnC, $D
		dc.b 0, $1B
		dc.b btnR, $B
		dc.b 0, $2D
		dc.b btnC, 7
		dc.b 0, $20
		dc.b btnR, $20
		dc.b btnR+btnC, $11
		dc.b 0, $2B
		dc.b btnL, $13
		dc.b 0, $D
		dc.b btnR, $1E
		dc.b btnR+btnC, 3
		dc.b btnC, 6
		dc.b 0, $16
		dc.b btnL, $D
		dc.b btnL+btnUp, 0
		dc.b btnL, 0
		dc.b 0, 8
		dc.b btnR, 0
		dc.b btnR+btnC, $C
		dc.b btnR, 1
		dc.b 0, $1C
		dc.b btnR, $28
		dc.b btnR+btnC, $16
		dc.b btnR, 4
		dc.b 0, $13
		dc.b btnR, $29
		dc.b 0, $A
		dc.b btnR, $A
		dc.b btnR+btnC, $10
		dc.b btnR, 1
		dc.b 0, 4
		dc.b btnR, $1E
		dc.b 0, $4A