		dc.b 0, $79
		dc.b btnR, $14
		dc.b btnR+btnC, 5
		dc.b btnR, $70
		dc.b 0, $23
		dc.b btnL, 5
		dc.b btnL+btnC, 6
		dc.b btnL, $61
		dc.b btnL+btnC, 6
		dc.b btnL, $30
		dc.b 0, $16
		dc.b btnL, $B
		dc.b btnL+btnC, $25
		dc.b btnL, $1D
		dc.b btnL+btnC, 7
		dc.b btnL, 15
		dc.b 0, $CD
		dc.b btnR, 3
		dc.b btnR+btnC, 6
		dc.b btnR, $4E
		dc.b 0, $5E
		dc.b btnR+btnC, 5
		dc.b btnR, 7
		dc.b 0, $B
		dc.b btnR, 8
		dc.b 0, $1A
		dc.b btnR, $1D
		dc.b 0, $66
		dc.b btnR, $12
		dc.b btnR+btnC, 7
		dc.b btnR, $2C
		dc.b 0, $22
		dc.b btnC, $13
		dc.b 0, 5
		dc.b btnC, 5
		dc.b btnR+btnC, $20
		dc.b btnR, $B
		dc.b btnR+btnC, 7
		dc.b btnR, $12
		dc.b 0, $52
		dc.b btnC, 16
		dc.b 0, 12
		dc.b btnC, $17
		dc.b 0, $1E
		dc.b btnL, $1E
		dc.b btnL+btnC, $14
		dc.b btnL, 3
		dc.b btnL+btnC, $28
		dc.b btnL, $2B
		dc.b btnL+btnC, 10
		dc.b btnL, 3
		dc.b 0, $19
		dc.b btnC, $1F
		dc.b btnR+btnC, 1
		dc.b btnR, $1B
		dc.b 0, 0