		dc.b 0, $16
		dc.b btnR, $2A
		dc.b btnR+btnC, $10
		dc.b btnR, $63
		dc.b btnR+btnC, 2
		dc.b btnC, $B
		dc.b 0, $1F
		dc.b btnR, 2
		dc.b btnR+btnC, $E
		dc.b btnR, $16
		dc.b 0, $20
		dc.b btnC, 0
		dc.b btnR+btnC, $1B
		dc.b 0, $27
		dc.b btnC, 0
		dc.b btnR+btnC, $A
		dc.b btnR, 6
		dc.b 0, $27
		dc.b btnR, 1
		dc.b btnR+btnC, $15
		dc.b 0, $1D
		dc.b btnR, 0
		dc.b btnR+btnC, $A
		dc.b 0, $1A
		dc.b btnR, $19
		dc.b btnR+btnC, $C
		dc.b btnR, $25
		dc.b 0, $C
		dc.b btnR, 0
		dc.b btnR+btnC, $C
		dc.b btnR, $26
		dc.b btnR+btnC, $A
		dc.b btnC, 0
		dc.b 0, 1
		dc.b btnC, 1
		dc.b btnR+btnC, 6
		dc.b btnR, 8
		dc.b 0, $12
		dc.b btnC, $17
		dc.b 0, $23
		dc.b btnR, $17
		dc.b 0, $17
		dc.b btnR+btnC, 9
		dc.b 0, $40
		dc.b btnR, 0
		dc.b btnR+btnC, 5
		dc.b btnC, 1
		dc.b 0, $F
		dc.b btnR, $19
		dc.b 0, $3E
		dc.b btnR, 6
		dc.b btnR+btnB+btnC, 7
		dc.b btnR+btnC, 6
		dc.b btnR, $2C
		dc.b btnR+btnC, 2
		dc.b btnC, 4
		dc.b 0, $13
		dc.b btnR, $10
		dc.b 0, $E
		dc.b btnC, $12
		dc.b btnR+btnC, 4
		dc.b btnR, 1
		dc.b 0, $1D
		dc.b btnR, $14
		dc.b btnR+btnC, 0
		dc.b btnC, 7
		dc.b 0, 7
		dc.b btnR, $12
		dc.b 0, $14
		dc.b btnR, 6
		dc.b btnR+btnC, 4
		dc.b btnC, 2
		dc.b 0, $10
		dc.b btnR, $1A
		dc.b 0, $25
		dc.b btnR, $18
		dc.b 0, $18
		dc.b btnL, $21
		dc.b 0, 5
		dc.b btnL, $1F
		dc.b 0, $E
		dc.b btnL, $B
		dc.b 0, $3C
		dc.b btnL, $31
		dc.b 0, $49
		dc.b btnL, 0
		dc.b btnL+btnC, 6
		dc.b btnL, $21
		dc.b 0, $AF